<div class="block block-vertnav block-brands">
    <div class="header">
        <h3>Brands</h3>
    </div>
    <div class="body">
        <?php foreach(Mage::registry('brands') as $brand): ?>
            <?php if($brand->getShowInFront()): ?>
                <a class="brand" href="/brands/<?=$brand->getUrlkey() . Mage::getStoreConfig('catalog/seo/product_url_suffix')?>" title="<?=$this->escapeHtml($brand->getName())?>">
                    <?php if(trim($brand->getImage())!='') : ?>
                        <div class="logo"><img src="<?=Mage::getBaseUrl('media') . $brand->getImage() ?>" title="<?=$this->escapeHtml($brand->getName())?>" alt="Logo for <?=$this->escapeHtml($brand->getName())?>" /></div>
                    <?php endif; ?>
                    <div class="title"><h4><?=$this->escapeHtml($brand->getName())?></h4></div>
                    <div class="description"><?=$brand->getDescription()?></div>
                </a>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
